### ISSUE TITLE
Pegasus expects JSON, data is null when loading xml

### ISSUE THREAD

**Issue by Eschon** [typicode/pegasus#18]
As the title says data is null when I load an xml file.
Looking at the code the reason for this is obvious:
https://github.com/typicode/pegasus/blob/master/src/pegasus.js#L32
You expect the loaded data to be JSON and if it fails to parse you just set it to null.
Is this intentional? If so shouldn't it be documented somewhere?
Wouldn't it be better if you just set data to responseText when it fails to parse?

For now I use this workaround:
```JavaScript
pegasus(`/my.xml`).then((data, xhr) => {
    parseXML(xhr.responseText);
});
```

**Comment by typicode** [comment]
Hi @Eschon,

It's intentional. To reduce the overall size of the lib, `pegasus` is only focused on `GET + JSON`.
The idea is that the smaller it is, the faster it can start making requests.

Sorry, you're right about the documentation. I'll try to improve it.

About `data`, personally I think it's easier if it's always the same type (`object`). You don't have to check its type, it's either `null` or an `object`.

But originally, I was thinking of just returning `xhr` and let users retrieve data using `xhr.response`. Unfortunately, some browsers still don't support `xhr.responseType = 'json'` so it wasn't possible. That's why I've added `data` as a convenience.

BTW wasn't thinking that it was possible to make pegasus work with `XML`, nice workaround :+1:

**Comment by Eschon** [comment]
Hi @typicode,

Thanks for making this clear. The library being small was one reason I chose it so I think it's ok if it stays like this as long as my workaround works.

**Comment by typicode** [comment]
You're welcome :)
